active_personality_id: 0
auto_save: true
auto_update: false
binding_name: null
ctx_size: 2048
data_vectorization_activate: true
data_vectorization_build_keys_words: false
data_vectorization_chunk_size: 512
data_vectorization_method: ftidf_vectorizer
data_vectorization_nb_chunks: 2
data_vectorization_overlap_size: 128
data_vectorization_save_db: false
data_visualization_method: PCA
debug: false
discussion_prompt_separator: '!@>'
enable_gpu: true
extensions: []
host: localhost
min_n_predict: 256
model_name: null
n_predict: 1024
n_threads: 8
override_personality_model_parameters: false
personalities:
- generic/lollms
port: 9601
repeat_last_n: 40
repeat_penalty: 1.2
seed: -1
temperature: 0.9
top_k: 50
top_p: 0.95
use_files: true
use_user_name_in_discussions: false
user_avatar: default_user
user_description: ''
user_name: user
version: 26
